paths:
  /user/stores:
    post:
      tags:
        - User
      summary: 특정 지역에 가게 추가하기
      parameters:
      - name: add store
        in: body
        required: true
        schema:
          properties:
            user:
              type: string
              description: 유저 이름
              example: user3
            store_id:
              type: string
              description: 가게 아이디
              example: store3000
            area:
              type: array
              description: 특정 지역
              example: [서울, 인천, 경기, 대구, 대전, 광주, 충청, 전라, 강원, 경상, 제주]
            
      
  /user/stores/reviews:
    post:
      tags:
        - User
      summary: 가게에 리뷰 추가하기
      parameters:
      - name: add review
        in: body
        required: true
        schema:
          properties:
            user:
              type: string
              description: 유저 이름
              example: user3
            store_id:
              type: string
              description: 가게 아이디
              example: store3000
            review:
              type: string
              description: 가게 리뷰
              example: good!!
      
  /user/stores/missons:
    post:
      tags:
        - User
      summary: 가게에 미션 추가하기
      parameters:
      - name: add mission
        in: body
        required: true
        schema:
          properties:
            user:
              type: string
              description: 유저 이름
              example: user3
            store_id:
              type: string
              description: 가게 아이디
              example: store3000
            mission:
              type: string
              description: 미션 이름
              example: 추가 방문하기
            mission_id:
              type: string
              description: 미션 아이디
              example: mission_id
            

  /user/stores/{store_id}/missions/{mission_id}/challenges/:
    post:
      tags:
        - User
      summary: 가게의 미션을 도전 중인 미션에 추가(미션 도전하기)API
      parameters:
      - name: add store mission into challenges
        in: body
        required: true
        schema:
          properties:
            user:
              type: string
              description: 유저 이름
              example: suser3
            store_id:
              type: string
              description: 가게 아이디
              example: store3000
            missions:
              type: array
              description: 도전 중인 미션들
              example: 추가 방문하기
            challenge: 
              type: string
              description: 도전하기
              example: [A가게 방문하기, B가게 추가 방문하기, C가게 재방문하기]

              















            
      responses:
        '200':
          description: 가게 방문 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "email": "swaggerTest@mail.com",
                  "name": "swagger",
                  "preferCategory": [
                    "한식",
                    "일식"
                  ]
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.